version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        image: digitalocean.com/php
        networks:
            - app-network
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    db:
        container_name: db
        image: mysql:5.7.22
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        restart: unless-stopped
        tty: true
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        networks:
            - app-network
    webserver:
        container_name: webserver
        image: nginx:alpine
        networks:
            - app-network
        ports:
            - '${APP_HTTP_PORT:-80}:80'
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
            
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
